/**
 * Customer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Customer { 
    customerId?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    contactNo?: number;
}

