/**
 * Customer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorResponseType } from './errorResponseType';


/**
 * 
 */
export interface ErrorResponse { 
    /**
     * abc123xyz
     */
    traceId?: string;
    message?: string;
    timestamp?: string;
    errorResponseType?: ErrorResponseType;
}
export namespace ErrorResponse {
}


