/**
 * Customer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export const ErrorResponseType = {
    BadRequestResponse: 'BadRequestResponse',
    UnauthorizedResponse: 'UnauthorizedResponse',
    ForbiddenResponse: 'ForbiddenResponse',
    NotFoundResponse: 'NotFoundResponse',
    ConflictResponse: 'ConflictResponse',
    InternalServerErrorResponse: 'InternalServerErrorResponse',
    ServiceUnavailableResponse: 'ServiceUnavailableResponse',
    TechnicalError: 'TECHNICAL_ERROR',
    UnknownError: 'UNKNOWN_ERROR',
    BusinessError: 'BUSINESS_ERROR'
} as const;
export type ErrorResponseType = typeof ErrorResponseType[keyof typeof ErrorResponseType];

